# Minecraft Server Configuration

Java:
  IP: "play.sapling.gg"
  Port: 25565
  DisplayName: "Java Edition"
Bedrock:
  IP: "play.sapling.gg"
  Port: 19132
  DisplayName: "Bedrock Edition"

Embed:
  Color: "#57F287" 
  OfflineColor: "#ED4245" 


