# +==================================================================================+
# |                                                                                  |
# |   __     __               _     _                 _       _     _                |
# |   \ \   / /__  _   _  ___| |__ | | ___ _   _     / \   __| | __| | ___  _ __     |
# |    \ \ / / _ \| | | |/ __| '_ \| |/ _ \ | | |   / _ \ / _` |/ _` |/ _ \| '_ \    |
# |     \ V / (_) | |_| | (__| | | | |  __/ |_| |  / ___ \ (_| | (_| | (_) | | | |   |
# |      \_/ \___/ \__,_|\___|_| |_|_|\___|\__, | /_/   \_\__,_|\__,_|\___/|_| |_|   |
# |                                        |___/                                     |
# |                                                                                  |
# |                        Vouchley Addon for SupportBot                             |
# |                         Created by Emerald Services                              |
# |                                                                                  |
# +==================================================================================+

Vouchley:
  API_Key: "REQUEST_API_KEY_BELOW"

# Vouchley API Documentation: https://www.vouchley.com/docs/api/getting-started
# To use the API you will need an API key. To get this create a ticket in https://discord.gg/buzz

Embed:
  Colour: 0x6063fc # 0x<hexcode> without the #
  Ephermal: true # Make the profile searches hidden so only the interacting user can see them.

Command:
  Name: "vouchley" # The name of the command (/vouchley)
  Description: "Search a Vouchley Profile." # The description of the command (/vouchley)
  Permissions: ["SendMessages"]