#      ___                            _    ___        _
#    / __> _ _  ___  ___  ___  _ _ _| |_ | . > ___ _| |_
#     \__ \| | || . \| . \/ . \| '_> | |  | . \/ . \ | |
#     <___/`___||  _/|  _/\___/|_|   |_|  |___/\___/ |_|
#                |_|  |_|
#
#           SupportBot created by Emerald Services
#           Installed with MIT License
#
#           Discord Support: https://dsc.gg/emerald-dev
#           Official Documentation: https://emeraldsrv.dev/wiki
#           Third-Party Documentation: https://emeraldsrv.dev/third-party
#
#           Command Configuration

Help:
  Command: "help"
  Description: "Get a list of all the commands."
  Permission: ["SendMessages"]
  Enabled: true

Info:
  Command: "info"
  Description: "Get information about the **ServerName**."
  Permission: ["SendMessages"]
  Enabled: true

TicketAdd:
  Command: "add"
  Description: "Add a user to a ticket."
  Permission: ["SendMessages"]
  Enabled: false

TicketRemove:
  Command: "remove"
  Description: "Remove a user from a ticket."
  Permission: ["SendMessages"]
  Enabled: true

OpenTicket:
  Command: "ticket"
  Description: "Create a support ticket."
  Permission: ["SendMessages"]
  Enabled: true

CloseTicket:
  Command: "close"
  Description: "Close a support ticket"
  Permission: ["SendMessages"]
  Enabled: true

Suggestion:
  Command: "suggest"
  Description: "Create a suggestion."
  Permission: ["SendMessages"]
  Enabled: true

Embed:
  Command: "embed"
  Description: "Build a discord embed."
  Permission: ["SendMessages"]
  Enabled: true

Translate:
  Command: "translate"
  Description: "Translate something to english"
  Permission: ["SendMessages"]
  Enabled: false

UserInfo:
  Command: "userinfo"
  Description: "Get info about a user."
  Permission: ["SendMessages"]
  Enabled: true

Ping:
  Command: "ping"
  Description: "Pong."
  Permission: ["SendMessages"]
  Enabled: true

# ---------------------------------------
#   Command Description Configuration
# ---------------------------------------

BlacklistDesc: "Blacklist a user from creating Tickets."
TicketAddDesc: "Add a user to a support ticket."
TicketRemoveDesc: "Remove a user from a support ticket."
TranslateCommandDesc: "Translates the language provided, along with the abbreviation (2 char) long language code"
OpenTicketDesc: "Open a new support ticket."
CloseTicketDesc: "Close your support ticket."
InfoCommandDesc: "Get information about the brand."
PingCommandDesc: "Pong!"
HelpCommandDesc: "Get a list of all the commands."
EmbedCommandDesc: "Send a message as an embed."
SuggestCommandDesc: "Suggest a feature for the server."
UserInfoCommandDesc: "Get info about a user."
